version: '3.8'
services:
  api-tests-dev:
    build: .
    image: api-tests
    container_name: api-tests-dev
    volumes: 
      - $PWD/test-reports/dev:/api-test-automation/mochawesome-report/
    # network_mode: FOR HOST
    # networks: for specific networks defined
    network_mode: host
    # custom command to run the specific set of tests in the specific environment
    command: run BOOKS BOOKS_DEV
  api-tests-stg:
    build: .
    image: api-tests
    container_name: api-tests-stg
    volumes: 
      - $PWD/test-reports/stg:/api-test-automation/mochawesome-report/
    network_mode: host
    command: run BOOKS BOOKS_STG
  api-tests-prd:
    build: .
    image: api-tests
    container_name: api-tests-prd
    volumes: 
      - $PWD/test-reports/prd:/api-test-automation/mochawesome-report/
    network_mode: host
    command: run BOOKS BOOKS_PRD

# docker run -v $PWD/test-reports:/api-test-automation/mochawesome-report --network=host --rm api-tests run BOOKS BOOKS_DEV



